version: '3.8'

services:
  shit-patrol:
    build: .
    container_name: shit-patrol-app
    restart: "no"
    environment:
      - NODE_ENV=production
      # Database
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      # Spotify
      - SPOTIFY_CLIENT=${SPOTIFY_CLIENT}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SPOTIFY_REFRESH=${SPOTIFY_REFRESH}
      - PLAYLIST_ID=${PLAYLIST_ID}
      # Display for headless browser
      - DISPLAY=:99
    volumes:
      # Optional: Mount logs or data directory
      - ./logs:/app/logs
    # Uncomment if you need to expose a port
    # ports:
    #   - "3000:3000"
    # Add security options for browser
    security_opt:
      - seccomp:unconfined
    # Add shared memory for Chrome
    shm_size: '2g'
    # Optional: Add memory limits
    mem_limit: 2g
    # Optional: Add CPU limits
    cpus: '1.0'